### ISSUE TITLE
p2p code review

### ISSUE THREAD

**Issue by dili021** [dili021/ruby-enumerables#2]
Comments are welcome!

**Comment by Kyle-Law** [comment]
Great job building the enumerable methods! 
The branching issue can be easily solved by branching a branch named 'development' from master branch > Set 'development' branch as default branch > Send pull request from `develop` branch to `development` branch

**Comment by patriciachrysy** [comment]
Good job @dili021, but i have some few remarks:
- Name your module Enumerable just like the original as it can easily be extended
- I tested three functions and none of them is working for Range and Hash
- The my_all? function does not work for this test case: [1, 2, 3, 4].my_all?{|n| n%2==0}
