### ISSUE TITLE
p2p code review of rspec

### ISSUE THREAD

**Issue by dili021** [dili021/ruby-enumerables#6]

**Comment by patriciachrysy** [comment]
Good tests, clean code!!! Good job @dili021, just missing some negative cases as the TSE said.

**Comment by Kyle-Law** [comment]
Great job @dili021 building the rspec for your enumerable project! I like how you make your rspec file extremely clean by setting test cases at the top. Here are a few remarks from me:
- your master & develop branch is not aligned with your feature branch(22 commits but without rspec file), this may cause an error when you are trying to merge them.
- Add Class, Symbol, Enumerator test to my_all?
- Add Block, Regex, Enumerator test to my_any?
- Add Class, Symbol, Enumerator test to my_none?
- Add (1 param + block) test to my_inject

Aside from that, your project is extremely clean. Well done 👍 👍 👍

**Comment by dili021** [comment]
thanks for the input!
